version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: database-meteostation-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql