server:
  port: 8090
  servlet:
    context-path: /meteostation
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meteodata
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: meteostation
        dialect: org.hibernate.dialect.PostgreSQLDialect