server:
  port: 8090
  servlet:
    context-path: /meteo-station
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABAE}
    driver-class-name: org.postgresql.Driver
    username: ${PGUSER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: meteodata
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    template:
      retry:
        enabled: true
        max-attempts: 3
        max-interval: 10000
amqp:
  exchange:
    temperature: temperature-exchange
  routing-key:
    get-temperature-statistics: get-temperature
    save-temperature: save-temperature
