server:
  port: 8080
  servlet:
    context-path: /meteo-station/api
spring:
  rabbitmq:
    username: user
    password: pass
    host: rabbitmq
    port: 5672
    template:
      routing-key: temperature_routing_key
      exchange: temperature_exchange
      retry:
        enabled: true
        max-attempts: 3
        max-interval: 10000
    publisher-returns: true
    publisher-confirm-type: simple