server:
  servlet:
    context-path: /meteostation
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: meteostation
        dialect: org.hibernate.dialect.PostgreSQLDialect