server:
  servlet:
    context-path: /meteo-station/api
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: meteodata
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq
    port: 5672
    template:
      retry:
        enabled: true
        max-attempts: 3
        max-interval: 10000
amqp:
  exchange:
    temperature: temperature-exchange
  routing-key:
    get-temperature-statistics: get-temperature
    save-temperature: save-temperature